world_address="0x044508ff3a94c19844702f34dd64c5a933870116a42ac1105fd324335ca7b3f9"
rpc="https://api.cartridge.gg/x/godot-demo-rookie/katana"
[runner]
explorer= false
check_contracts= true
[indexing]
pending= true
polling_interval= 500
max_concurrent_tasks= 100
transactions= true
contracts=[]
namespaces=[]
world_block= 0
controllers= true
strict_model_reader= false
[events]
raw= true
[erc]
max_metadata_tasks= 10
[sql]
all_model_indices= true
historical= []
page_size= 32768
cache_size= -500000
